export const mockProperties = [
  {
    id: "1",
    title: "142 Ridgewood Ave",
    address: "142 Ridgewood Ave, Beverly Hills, CA 90210",
    city: "Beverly Hills",
    price: 2850000,
    beds: 5,
    baths: 4,
    sqft: 4200,
    tag: "New",
    images: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&q=85",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=85",
    ],
    neighborhood_scores: {
      school: 9.2,
      safety: 8.8,
      transit: 7.5,
      amenities: 9.0,
      priceGrowth: 18.4,
      daysOnMarket: 14,
    },
  },
  {
    id: "2",
    title: "88 Maple Canyon Dr",
    address: "88 Maple Canyon Dr, Scottsdale, AZ 85251",
    city: "Scottsdale",
    price: 1490000,
    beds: 4,
    baths: 3,
    sqft: 3100,
    tag: "Exclusive",
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=85",
    ],
    neighborhood_scores: {
      school: 8.5,
      safety: 9.0,
      transit: 6.8,
      amenities: 8.5,
      priceGrowth: 12.0,
      daysOnMarket: 22,
    },
  },
  {
    id: "3",
    title: "7 Clover Hill Rd",
    address: "7 Clover Hill Rd, Austin, TX 78701",
    city: "Austin",
    price: 975000,
    beds: 3,
    baths: 2,
    sqft: 2400,
    tag: "Price Drop",
    images: [
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=85",
    ],
    neighborhood_scores: {
      school: 9.0,
      safety: 8.2,
      transit: 8.0,
      amenities: 9.2,
      priceGrowth: 15.1,
      daysOnMarket: 10,
    },
  },
];

export const mockBookings = [
  {
    id: "1",
    name: "Sarah Jenkins",
    email: "sarah@example.com",
    phone: "555-0199",
    property_interest: "142 Ridgewood Ave",
    preferred_slot: "Mon 10am",
    created_at: "2026-03-14T10:00:00Z",
  },
  {
    id: "2",
    name: "David Miller",
    email: "david@example.com",
    phone: "555-0122",
    property_interest: "88 Maple Canyon Dr",
    preferred_slot: "Tue 2pm",
    created_at: "2026-03-14T11:30:00Z",
  },
];

export const mockRooms = [
  {
    id: "r1",
    property_id: "1",
    name: "Living Room",
    description: "18×22 ft open plan. South-facing bay windows, oak hardwood floors, marble fireplace.",
    video_url: null,
    hotspot_x: "27%",
    hotspot_y: "31%",
  },
  {
    id: "r2",
    property_id: "1",
    name: "Master Suite",
    description: "1,100 sq ft. Walk-in wardrobe, en-suite marble bathroom, private balcony.",
    video_url: null,
    hotspot_x: "64%",
    hotspot_y: "23%",
  },
  {
    id: "r3",
    property_id: "1",
    name: "Kitchen",
    description: "Chef's island. Quartz countertops, Sub-Zero fridge, double Miele oven, butler's pantry.",
    video_url: null,
    hotspot_x: "41%",
    hotspot_y: "61%",
  },
  {
    id: "r4",
    property_id: "1",
    name: "Garden & Pool",
    description: "0.4 acre landscaped. Heated infinity pool, outdoor kitchen, mature oak trees.",
    video_url: null,
    hotspot_x: "75%",
    hotspot_y: "67%",
  },
  {
    id: "r5",
    property_id: "1",
    name: "Home Office",
    description: "Soundproofed. Built-in shelving, fiber broadband, private garden entrance.",
    video_url: null,
    hotspot_x: "17%",
    hotspot_y: "73%",
  },
];
